### PR TITLE
Fix zh_cn.json and a small request

### PR DESCRIPTION
**Pull request by Imbarainbow**
This a fix of zh_cn.json for age of exile . And I'm wondering that if I can repost Age of Exile to a Chinese forum , you know , because of GFW , it's hard for we Chinese players to know some good mods.This is an excellent mod,and I hope more Chinese player will know it. I will link to curseforge pages and will keep everything you have asked.

### CODE REVIEW

**Comment by Imbarainbow** [comment]
And there is also a question that , can Age of Exile make the mob generate due to the level of the player nearby just like Mine And Slash

**Comment by RobertSkalko** [comment]
Yes to mob lvl to player, the config is now a datapack.
And you can post it to chinese sites as long as there's a link to my curseforge.

**Comment by Imbarainbow** [comment]
Emmmm, where can I find this datapack to change it

**Comment by RobertSkalko** [comment]
Learn about vanilla minecraft datapacks.

**Pull request merged**
